// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcyjlxrrjpiqxhgljmxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjeWpseHJyanBpcXhoZ2xqbXhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NjQ5MDIsImV4cCI6MjA3MjE0MDkwMn0.YHIDoW10Zs_a9xGbmq0hSsy024T2F9df8T9yejQlga4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});