name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Build Docker image
      run: docker build -t equityleap-app .

    - name: Deploy to server
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Find the equity-leap directory
          if [ -d "/root/equity-leap" ]; then
            cd /root/equity-leap
          elif [ -d "/home/$USER/equity-leap" ]; then
            cd /home/$USER/equity-leap
          elif [ -d "equity-leap" ]; then
            cd equity-leap
          else
            echo "equity-leap directory not found"
            exit 1
          fi
          
          # Pull latest changes
          git pull origin main
          
          # Stop and remove existing container
          sudo docker stop equityleap-container || true
          sudo docker rm equityleap-container || true
          
          # Build and run new container
          sudo docker build -t equityleap-app .
          sudo docker run -d --name equityleap-container -p 80:80 equityleap-app
