name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Build Docker image
      run: docker build -t equityleap-app .

    - name: Setup and Deploy to server
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "=== DEPLOYMENT STARTED ==="
          echo "User: $(whoami)"
          echo "Home: $HOME"
          echo "Current directory: $(pwd)"
          
          # Check if Docker is installed
          if ! command -v docker &> /dev/null; then
            echo "Installing Docker..."
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            sudo usermod -aG docker $USER
            rm get-docker.sh
          fi
          
          # Ensure Docker service is running
          sudo systemctl start docker || true
          sudo systemctl enable docker || true
          
          # Clone repository if it doesn't exist
          if [ ! -d "equity-leap" ]; then
            echo "Cloning repository..."
            git clone https://github.com/PavitarSinghArneja/equity-leap.git
          fi
          
          # Navigate to project directory
          cd equity-leap
          
          # Pull latest changes
          echo "Pulling latest changes..."
          git pull origin main
          
          # Stop and remove existing container (with sudo if needed)
          echo "Stopping existing container..."
          sudo docker stop equityleap-container 2>/dev/null || docker stop equityleap-container 2>/dev/null || true
          sudo docker rm equityleap-container 2>/dev/null || docker rm equityleap-container 2>/dev/null || true
          
          # Build new container (try with sudo first, then without)
          echo "Building Docker image..."
          if sudo docker build -t equityleap-app . 2>/dev/null; then
            echo "Built with sudo"
            DOCKER_CMD="sudo docker"
          elif docker build -t equityleap-app . 2>/dev/null; then
            echo "Built without sudo"
            DOCKER_CMD="docker"
          else
            echo "Docker build failed"
            exit 1
          fi
          
          # Run new container
          echo "Starting new container..."
          $DOCKER_CMD run -d --name equityleap-container -p 80:80 equityleap-app
          
          # Verify container is running
          echo "=== CONTAINER STATUS ==="
          $DOCKER_CMD ps | grep equityleap-container || echo "Container not found"
          
          echo "=== DEPLOYMENT COMPLETED ==="
