name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Build Docker image
      run: docker build -t equityleap-app .

    - name: Deploy to server
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          set -e
          echo "=== STARTING DEPLOYMENT ==="
          
          # Install Docker if not present
          if ! command -v docker >/dev/null 2>&1; then
            echo "Installing Docker..."
            curl -fsSL https://get.docker.com | sudo sh
            sudo usermod -aG docker $USER
          fi
          
          # Start Docker service
          sudo systemctl start docker 2>/dev/null || true
          
          # Clone or update repository
          if [ ! -d "equity-leap" ]; then
            echo "Cloning repository..."
            git clone https://github.com/PavitarSinghArneja/equity-leap.git
          else
            echo "Updating repository..."
            cd equity-leap
            git pull origin main
            cd ..
          fi
          
          cd equity-leap
          
          # Stop existing container
          echo "Stopping existing containers..."
          sudo docker stop equityleap-container 2>/dev/null || true
          sudo docker rm equityleap-container 2>/dev/null || true
          
          # Build and run
          echo "Building Docker image..."
          sudo docker build -t equityleap-app .
          
          echo "Starting container..."
          sudo docker run -d --name equityleap-container -p 80:80 --restart unless-stopped equityleap-app
          
          # Check if container started
          if sudo docker ps | grep equityleap-container; then
            echo "=== DEPLOYMENT SUCCESS ==="
          else
            echo "=== DEPLOYMENT FAILED - Container not running ==="
            sudo docker logs equityleap-container
            exit 1
          fi
